services:
  web:
    build:
      context: .
    command: python run.py
    env_file:
      - .env
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /project
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pg-data:/var/lib/postgresql/data 

  redis:
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  pg-data: