services:
  web:
    build:
      context: .
    command: python app.py
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: